matrix:
  include:
    - language: python
      python: 3.7
      services:
        - mysql
      before_install:
        - mysql -e 'CREATE DATABASE YesOKTest;'
      install:
        - cd backend/
        - pip install -r requirements.txt
      script:
        - export PYTHONPATH=`pwd`:$PYTHONPATH
        - pytest

    - language: node_js
      node_js:
        - 14
      before_script:
        - cd frontend
        - yarn install
      script:
        - yarn test --coverage
      after_script:
        - COVERALLS_REPO_TOKEN=1zhoh7CB1VGzg1Z2BC1R6DuVe8kTBObpP yarn coveralls

notifications:
  email:
    - dq2146@columbia.edu
