matrix:
  include:
    - language: node_js
      node_js:
        - 14
      before_script:
        - cd frontend
        - yarn install
      script:
        - yarn test --coverage --REACT_APP_GMAP_KEY=$GMAP_KEY
      after_success:
        - yarn coveralls

    - language: python
      python: 3.7
      services:
        - mysql
      before_install:
        - wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
        - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
        - sudo apt-get update -q
        - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
        - sudo systemctl restart mysql
        - sudo mysql_upgrade
        - mysql --version
        - mysql -e 'CREATE DATABASE YesOKTest;'
        - mysql -e 'SET GLOBAL log_bin_trust_function_creators = 1;'
      install:
        - cd backend/
        - pip install -r requirements.txt
      script:
        - export PYTHONPATH=`pwd`:$PYTHONPATH
        - pytest --cov=. tests
      after_success:
        - coveralls

notifications:
  webhooks:
    - https://coveralls.io/webhook
